module.exports = {
  TEST_EVENT: "TEST_EVENT",
  TEST_RESPONSE: "TEST_RESPONSE",
  LOCAL_CHAT: "LOCAL_CHAT",
  USER_CONNECTED: "USER_CONNECTED",
  MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
  MESSAGE_SENT: "MESSAGE_SENT",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  TYPING: "TYPING",
  VERIFY_USER: "VERIFY_USER",
  LOGOUT: "LOGOUT",
  USERS: "USERS"
};
